/*
 * New Spec - OpenAPI 3.0
 *
 * This is a sample description about this spec.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv2AuthLoginPostResponse1 {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    #[serde(rename = "statusText", skip_serializing_if = "Option::is_none")]
    pub status_text: Option<String>,
}

impl Apiv2AuthLoginPostResponse1 {
    pub fn new() -> Apiv2AuthLoginPostResponse1 {
        Apiv2AuthLoginPostResponse1 {
            reason: None,
            status_code: None,
            status_text: None,
        }
    }
}


