/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2DeviceLicenseActivate200ResponseData {
    #[serde(rename = "sessionId", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

impl PostApiV2DeviceLicenseActivate200ResponseData {
    pub fn new() -> PostApiV2DeviceLicenseActivate200ResponseData {
        PostApiV2DeviceLicenseActivate200ResponseData { session_id: None }
    }
}
