/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2DeviceLicenseValidate200ResponseData {
    #[serde(rename = "isValid", skip_serializing_if = "Option::is_none")]
    pub is_valid: Option<bool>,
}

impl PostApiV2DeviceLicenseValidate200ResponseData {
    pub fn new() -> PostApiV2DeviceLicenseValidate200ResponseData {
        PostApiV2DeviceLicenseValidate200ResponseData { is_valid: None }
    }
}
