/*
 * FLECS Console API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV2TokensRequestToken {
    #[serde(rename = "app")]
    pub app: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl PostApiV2TokensRequestToken {
    pub fn new(app: String, version: String) -> PostApiV2TokensRequestToken {
        PostApiV2TokensRequestToken {
            app,
            version,
        }
    }
}


